- name: install mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: enable and start mysql service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: change default root password   
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}